<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <style type="text/css">
            * {padding: 0 0; margin: 0 0; font-family: Helvetica, sans-serif;}
            .header
            {
                background: #FFF;
            }
            
            .user
            {
                float: right;
                padding-right: 5px;
            }
            
            .breadcrumbs
            {
                background:#EFEFEF;
                padding-top: 10px;
                padding-left: 5px;
            }
            .content 
            {
                margin: 5px;
            }
            .topnav
            {
                padding: 5px ;
            }

            .topnav ul , .topnav ul li
            {
                display: inline;
            }		
            .topnav ul li a
            {
                color: #00E;
                text-decoration: none;
                border-width: 1px 1px 0px 1px;
                border-color: #000;
                border-style: solid;
                padding: 5px;
            }
            .topnav ul li a:hover
            {
                background: #CCC;
            }
            body
            {
                background: #DDD;
            }

        </style>

    </head>
<?php $user = Zend_Auth::getInstance()->getIdentity();?>
    <body>
        <div class="header">
            <h1>
                Introduction to Zend_Navigation
            </h1>
            <div class="user">
                Hello <?php echo $user->name;?> | <a href="<?php echo $this->url(array("action"=>'logout',"controller"=>'user',"module"=>'default'))?>">Logout</a>
            </div>
                <div class="topnav">
                    <?php echo $this->navigation()->menu(); ?>
                </div>
                <div class="breadcrumbs">
                    <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" : "); ?>
                </div>
            </div>
            <div class="content">
                <?php echo $this->layout()->content; ?>
            </div>
    </body>
</html>