<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <style type="text/css">
            * {padding: 0 0; margin: 0 0; font-family: Helvetica, sans-serif;}
            .header
            {
                background: #FFF;
                float:left;
                width:100%;
            }
            
            .user
            {
                float: right;
                padding-right: 5px;
            }
            
            .content 
            {
                margin: 5px;
            }
            
            body
            {
                background: #DDD;
            }

        </style>
    </head>
    <body>
        <div class="header">
            <h1>Zend Framework Sample Structure</h1>
            <div class="user"><?php echo $this->render('_auth.phtml') ?></div>
        </div>
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>